version: '3'
services:
  webserver:
    build: .
    expose:
      - "80"
    environment:
      DIGITALOCEAN_ACCESS_TOKEN: ${DIGITALOCEAN_ACCESS_TOKEN}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    env_file:
      - .env
    networks:
      - docker-network

  nginx:
    image: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log/error.log
      - ./nginx/cache:/etc/nginx/cache
    #      - ./data/certbot/conf:/etc/letsencrypt
    #     - ./data/certbot/www:/var/www/certbot
    networks:
      - docker-network
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  docker-network:
