---
- name: Allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled

- name: Allow all access to udp port 500
  community.general.ufw:
    rule: allow
    port: '500'
    proto: udp

- name: Allow all access to udp port 4500
  community.general.ufw:
    rule: allow
    port: '4500'
    proto: udp

- name: Insert nat and mangle rule to the ufw before.rules
  blockinfile:
    path: /etc/ufw/before.rules
    marker: "#{mark} ANSIBLE MANAGED BLOCK nat rule"
    insertbefore: "Don't delete these required lines"
    block: |
      *nat
      -A POSTROUTING -s 10.10.10.0/24 -o eth0 -m policy --pol ipsec --dir out -j ACCEPT
      -A POSTROUTING -s 10.10.10.0/24 -o eth0 -j MASQUERADE
      COMMIT

      *mangle
      -A FORWARD --match policy --pol ipsec --dir in -s 10.10.10.0/24 -o eth0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360
      COMMIT

- name: Uncomment ip_forward
  replace:
    path: "/etc/ufw/sysctl.conf"
    regexp: "#net/ipv4/ip_forward=1"
    replace: "net/ipv4/ip_forward=1"


- name: Inserting the forwarding rules for traffic from the ipsec tunnel.
  blockinfile:
    path: /etc/ufw/before.rules
    marker: "#{mark} ANSIBLE MANAGED BLOCK forwarding rules"
    insertbefore: "allow all on loopback"
    block: |
      -A ufw-before-forward --match policy --pol ipsec --dir in --proto esp -s 10.10.10.0/24 -j ACCEPT
      -A ufw-before-forward --match policy --pol ipsec --dir out --proto esp -d 10.10.10.0/24 -j ACCEPT

- name: Add mappings to /etc/ufw/sysctl.conf
  blockinfile:
    path: /etc/ufw/sysctl.conf
    block: |
      {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    - { name: net/ipv4/ip_no_pmtu_disc=1 }
    - { name: net/ipv4/conf/all/send_redirects=0 }
    - { name: net/ipv4/conf/all/accept_redirects=0 }

- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    state: enabled

- name: Reload service ufw
  ansible.builtin.service:
    name: ufw
    state: reloaded
